[project]
name = "visionworks"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.1",
    "django-htmx>=1.27.0",
    "numpy>=2.4.1",
    "opencv-python-headless>=4.11.0.86",
    "pillow>=12.1.0",
    "python-dotenv>=1.2.1",
]
